runtime: java11
instance_class: F1

handlers:

#- url: /(.*\.html)$
#  static_files: \1
#  upload: .*\.html$
  
#- url: /images
#  static_dir: images
  
#- url: /css
#  static_dir: css
  
#- url: /js
#  static_dir: js
  
#- url: /static
#  static_dir: static

- url: /(Admin|DataStoreCleaner|cloud-datastore-export|Edit|EraseEntity|contacts|messages|ReportScore|ResponseServlet)
  secure: always
  login: admin
  script: auto

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

