runtime: java21
instance_class: F2

inbound_services:
- warmup
automatic_scaling:
#  min_instances: 1
  max_instances: 5

#default_expiration: 1m

# The following handlers cause appengine to upload copies of the static files to Gooogle Cloud Storage and serve them from there
# URL requests for these files are handled by the App Engine infrastructure directly, and do not reach the language runtime of the application.

handlers:

# Map all .html files to static copies
- url: (/.*\.html)
  static_files: classes/META-INF/resources\1
  upload: classes/META-INF/resources/.*\.html
  require_matching_file: True
  secure: always

# Map everything in the css directory to static copies  
- url: /css
  static_dir: classes/META-INF/resources/css
  require_matching_file: True
  secure: always

# Map everything in the images directory to static copies  
- url: /images
  static_dir: classes/META-INF/resources/images
  require_matching_file: True
  secure: always
  
# Map everything in the error directory to static copies  
- url: /error
  static_dir: classes/META-INF/resources/error
  require_matching_file: True
  
# Map everything in the js directory to static copies  
- url: /js
  static_dir: classes/META-INF/resources/js
  require_matching_file: True
  secure: always
  
# Map everything in the docs directory to static copies  
- url: /docs
  static_dir: classes/META-INF/resources/docs
  require_matching_file: True
  secure: always

# All requests to the following URLs are restricted to admins or service accounts
# NOTE: The associated Java classes (Admin, DataStoreCleaner, Edit, etc.) ALSO 
# perform redundant authentication checks as defense-in-depth.
# If this app.yaml rule is misconfigured or bypassed, the Java code will reject the request.
- url: /(Admin|DataStoreCleaner|Edit|EraseEntity|contacts|messages|ReportScore|ValidateQuestions)
  secure: always
  login: admin
  script: auto

# All other requests must be secure (TLS)
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

error_handlers:
  - file: clesses/META-INF/resources/error/404.html
